### ISSUE TITLE
Quantity loses value on Edit screen

### ISSUE THREAD

**Issue by MZMohamed** [SolidInvoice/SolidInvoice#342] opened 2020-10-13 09:12 UTC
**Describe the bug**
When editing an invoice with quantities more than 1, the quantities would reset to 1

**To Reproduce**
1. Go to Invoice
2. Click on any invoice with a quantity more than 1 to open it.
3. Click the Edit button on top.
4. The quantities that were more than 1 are now set to 1.

**Expected behavior**
The quantities should hold their value when clicking the edit button

**Screenshots**
### Before
![before_edit](https://user-images.githubusercontent.com/16529698/95840454-73ff9900-0d44-11eb-8d55-a96c1dad6e87.png)

###  After
![before_click_edit](https://user-images.githubusercontent.com/16529698/95840450-72ce6c00-0d44-11eb-85de-c14534a91fc2.png)

**Desktop (please complete the following information):**
- OS: [Windows 10]
- Browser [chrome]
- Version [Version 85.0.4183.121]

**Comment by pierredup** [comment] 2020-10-17 06:13
Hi @MZMohamed. Thank you for the report. This should already be fixed on the master branch.

**Comment by pierredup** [comment] 2020-10-22 06:00
Closing as duplicate of #303;

**Closed by pierredup** 2020-10-22 06:00 UTC
Labels: bug
