### ISSUE TITLE
The server returned a "500 Internal Server Error".

### ISSUE THREAD

**Issue by rongkn** [SolidInvoice/SolidInvoice#460] opened 2022-09-26 19:53 UTC
My install using docker  just quit working  and when I launched the application it comes up with the default config page and if you follow the steps it always bombs with 500 Internal Server error. I have saved the database folder in the file manager and recreated the install from scratch and still no mater what I try to do it always comes up with the 500 Internal Server Error. I have attached a couple of photos of what I get and cant get by it. I have had this Solid Invoice running with no issues for months and now this issue pops up. 
Hoping someone can help me get this back and operational
TIA
Ron G Knox

![solidinvoice](https://user-images.githubusercontent.com/32495778/192367172-b7b0e02d-c17a-49b7-a7af-bb8b1ea4fa12.JPG)
![solidinvoice1](https://user-images.githubusercontent.com/32495778/192367194-c657ab99-60a6-487b-b983-dd11cf697e04.JPG)

**Comment by mariushosting** [comment] 2022-09-26 23:00
@pierredup same error, already opened a ticket about the issue.

**Comment by pierredup** [comment] 2022-09-27 13:17
Closing as duplicate of #459

**Closed as not planned by pierredup** 2022-09-27 13:17 UTC
Labels: bug
